// SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
//
// SPDX-License-Identifier: Apache-2.0

package org.eclipse.lmos.arc.agents.events

import org.slf4j.LoggerFactory

/**
 * Handles events generated by Agents.
 * Mainly used for logging purposes.
 */
class LoggingEventHandler : EventHandler<Event> {

    private val log = LoggerFactory.getLogger(javaClass)

    override fun onEvent(event: Event) {
        log.debug("Event published: $event")
    }
}
